version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: qapqan
      POSTGRES_USER: qapqan
      POSTGRES_PASSWORD: qapqan
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
