version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
